before:
  hooks:
    - go mod tidy

builds:
  - id: pm
    main: .
    binary: pm
    ldflags:
      - -w -s
      - -extldflags "-static"
    tags:
      - release
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC_FOR_TARGET=gcc-aarch64-linux-gnu
          - CC=aarch64-linux-gnu-gcc

