before:
  hooks:
    - go mod tidy
builds:
  - id: pm
    main: .
    binary: pm
    ldflags:
      - -w -s
    tags:
      - release
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
checksum:
  disable: true
archives:
  - format: zip
