before:
  hooks:
    - go mod tidy
    - |
      TAG=$(git tag --points-at HEAD)
      sed -i "s/__VERSION__/$TAG/" cmds/root.go
builds:
  - id: pm
    main: .
    binary: pm
    ldflags:
      - -w -s
    tags:
      - release
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC_FOR_TARGET=gcc-aarch64-linux-gnu
          - CC=aarch64-linux-gnu-gcc
